version: '3.9'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    command: mongod --quiet --logpath /dev/null # be quiet mongo db!
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sparql_and_rdf

  web:
    build: .
    depends_on:
      - db
    container_name: notebook
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "80:80"
    volumes:
      - ./index.ipynb:/home/sparql/index.ipynb